apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasir-first-deployment
  labels:
    environment: production
    located : front-end-pods
spec:
  template:
    metadata:
      name: nasir-first-pod
      labels:
        environment: production
        located : front-end
    spec:
      containers:
        - name: nasir-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      located : front-end