# ###################################
# Help
def drawMyRuler(pdf):
    pdf.drawString(100,810, 'x100')
    pdf.drawString(200,810, 'x200')
    pdf.drawString(300,810, 'x300')
    pdf.drawString(400,810, 'x400')
    pdf.drawString(500,810, 'x500')
    pdf.drawString(10,100, 'y100')
    pdf.drawString(10,200, 'y200')
    pdf.drawString(10,300, 'y300')
    pdf.drawString(10,400, 'y400')
    pdf.drawString(10,500, 'y500')
    pdf.drawString(10,600, 'y600')
    pdf.drawString(10,700, 'y700')
    pdf.drawString(10,800, 'y800')    
# ###################################
# Content
fileName = 'MyDoc.pdf'
documentTitle = 'Clothing Bill'
title = 'Khader Fashions'
subTitle = 'The brand ever like'
textLines = [
'Following is the autogenerated Bill.',
'You can return unless you tear tags.',
'Visit Again :-).'
]
image = 'tasmanianDevil.jpg'

# ###################################
# 0) Create document 
from reportlab.pdfgen import canvas 

pdf = canvas.Canvas(fileName)
pdf.setTitle(documentTitle)
drawMyRuler(pdf)
# ###################################
# 1) Title :: Set fonts 
# # Print available fonts
# for font in pdf.getAvailableFonts():
#     print(font)

# Register a new font
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics

pdfmetrics.registerFont(
    TTFont('abc', 'SakBunderan.ttf')
)
pdf.setFont('abc', 36)
pdf.drawCentredString(350, 770, title)

# ###################################
# 2) Sub Title 
# RGB - Red Green and Blue
pdf.setFillColorRGB(255, 0, 255)
pdf.setFont("Courier-Bold", 24)
pdf.drawCentredString(350,720, subTitle)

# ###################################
# 3) Draw a line
pdf.line(30, 700, 550, 700)

# ###################################
# 4) Text object :: for large amounts of text
from reportlab.lib import colors

text = pdf.beginText(60, 670)
text.setFont("Courier", 18)
text.setFillColor(colors.red)
for line in textLines:
    text.textLine(line)

pdf.drawText(text)

# ###################################
# 5) Draw a logo
pdf.drawInlineImage(image, 20, 720)

##########
# 6) List of items in table
# List of Lists
data = [
    ['Dedicated Hosting', 'VPS Hosting', 'Sharing Hosting', 'Reseller Hosting' ],
  #  ['€200/Month', '€100/Month', '€20/Month', '€50/Month'],
   # ['Free Domain', 'Free Domain', 'Free Domain', 'Free Domain'],
    ['2GB DDR2', '20GB Disc Space']
]
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Table
table = Table(data)
# add style
from reportlab.platypus import TableStyle
from reportlab.lib import colors

style = TableStyle([
    ('BACKGROUND', (0,0), (3,0), colors.green),
    ('TEXTCOLOR',(0,0),(-1,0),colors.whitesmoke),

    ('ALIGN',(0,0),(-1,-1),'CENTER'),

    ('FONTNAME', (0,0), (-1,0), 'Courier-Bold'),
    ('FONTSIZE', (0,0), (-1,0), 14),

    ('BOTTOMPADDING', (0,0), (-1,0), 12),

    ('BACKGROUND',(0,1),(-1,-1),colors.beige),
])
table.setStyle(style)
# 2) Alternate backgroud color
rowNumb = len(data)
for i in range(1, rowNumb):
    if i % 2 == 0:
        bc = colors.burlywood
    else:
        bc = colors.beige
    
    ts = TableStyle(
        [('BACKGROUND', (0,i),(-1,i), bc)]
    )
    table.setStyle(ts)

# 3) Add borders
ts = TableStyle(
    [
    ('BOX',(0,0),(-1,-1),2,colors.black),

    ('LINEBEFORE',(2,1),(2,-1),2,colors.red),
    ('LINEABOVE',(0,2),(-1,2),2,colors.green),

    ('GRID',(0,1),(-1,-1),2,colors.black),
    ]
)
table.setStyle(ts)

elems = []
elems.append(table)

#pdf.build(elems)

pdf.save()